server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowCredentials: true

      routes:
        - id: CLIENT-SERVICE
          uri:  lb://CLIENT-SERVICE
          predicates:
            - Path=/client/**


        - id: CINEMA-SERVICE
          uri: lb://CINEMA-SERVICE
          predicates:
            - Path=/cinema/**


        - id: FILM-SERVICE
          uri: lb://FILM-SERVICE
          predicates:
            - Path=/film/**
          filters:
            - AuthenticationFilter

        - id: FILMSHOW-SERVICE
          uri: lb://FILMSHOW-SERVICE
          predicates:
            - Path=/filmShow/**
          filters:
            - AuthenticationFilter


        - id: IDENTITY-SERVICE
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**

        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employees/**
          filters:
            - AuthenticationFilter
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost